# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_data_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_es',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_en',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_es',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_es',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_en',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_es',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_en',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_es',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_es',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_en',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_es',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_en',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_es',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_en',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_es',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_en',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_es',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shapefilegroup',
            name='display_name',
            field=models.CharField(max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_en',
            field=models.CharField(max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_es',
            field=models.CharField(max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_en',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_es',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name',
            field=models.CharField(help_text='The name to show for this section', max_length=50, default=""),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_en',
            field=models.CharField(help_text='The name to show for this section', max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_es',
            field=models.CharField(help_text='The name to show for this section', max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name',
            field=models.CharField(help_text='The name to show for this section', max_length=50, default=''),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_en',
            field=models.CharField(help_text='The name to show for this section', max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_es',
            field=models.CharField(help_text='The name to show for this section', max_length=50, null=True, default=''),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_so',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_vi',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_ru',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_so',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_vi',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_ru',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_so',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_vi',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_ru',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_so',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_vi',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_ru',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_so',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_vi',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_so',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_vi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_so',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_vi',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_ru',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_so',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_vi',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ru',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_so',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_vi',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_ru',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_so',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_vi',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_ru',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_so',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_vi',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_ru',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_so',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_vi',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_ru',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_so',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_vi',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_ru',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_so',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_vi',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_so',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_cn',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_cn',
            field=models.CharField(help_text="A title for your important link, like 'Evacuation Information'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_name_cn',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='community_leaders_cn',
            field=models.TextField(default='Information about community leaders goes here.', help_text='Information about community leaders, how to contact them, and form groups.', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_cn',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_cn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_cn',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_cn',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_cn',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_cn',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_cn',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_cn',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsubsection',
            name='display_name_cn',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='text_cn',
            field=models.TextField(help_text='More information about building your supply kit. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_cn',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_en',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_es',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_ru',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_so',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='link_vi',
            field=models.TextField(help_text='Your link and any information about it. Any web address in here gets turned into a link automatically.', null=True),
        ),
    ]
